---
Name: app
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - themes/ss4demo/javascript/googleanalytics.js

SilverStripe\Security\Security:
  default_login_dest: admin/pages
